BUFFER_SIZE = 1<<16
SEGMENT_SIZE = 1<<15
WINDOW_SIZE = 8

CLIENT_IP = "localhost"
CLIENT_LISTEN_TIMEOUT = 30
# CLIENT_LISTEN_FILE_TRANSFER_TIMEOUT = 1

SERVER_IP = "localhost"
SERVER_LISTEN_TIMEOUT = 0.5


